### ISSUE TITLE
import path correction

### ISSUE THREAD

**Issue by sothy** [free5gc/amf#2]
Hello we need to correct import path in amf. For example,
"free5gc/lib/path_util"   ==> github.com/free5gc/path_util
All files should be changed

**Comment by free5gc-org** [comment]
Hi,

We have some plan to refactor our library and NF to be managed by go module. But that is not our first priority now.

Thanks for your recommend.

**Comment by calee0219** [comment]
hi @sothy ,

Why the path need to be change? I think "free5gc/lib/path_util" works fine on my computer?

**Comment by sothy** [comment]
@calee0219 
yes it shoud work. I am thinking of unified global path, so development can be simple. Isnnt it.?

**Comment by calee0219** [comment]
hmmm...

I'm not sure, what's the benefit of using global path?

**Comment by free5gc-org** [comment]
All import paths are changed with Go modules in the latest version.
