### ISSUE TITLE
Identity Procedure when UE GUTI is unknown

### ISSUE THREAD

**Issue by mrlnc** [free5gc/amf#63]
Last year I was PR'ing a patch: https://github.com/free5gc/amf/pull/28

> If UE registers with 5G-GUTI (it has a context), free5gc may search
> for a context on another AMF. If no context is found, it should
> signal that to UE to trigger re-registration. Otherwise the UE may use
> the (invalid) context again.

I think I made a mistake and misunderstood the standard; the behavior from the patch is wrong.

Current behavior:
If AMF cannot find a 5G-GUTI, it will send Registration Reject with cause "UE Identity cannot be derived".
That worked on the UE I tested last year, triggering a full re-attach.

Seems that NAS only specifies that cause for Service Request and Registration Update procedure, but not initial Registration Request.

Better:
If the AMF cannot interpret the GUTI, it should send an **Identity Request** for SUCI/IMSI. So the AMF would wait for the response and then carry on handling the initial Registration Request.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org @mrlnc 
I fixed this issue and sent a [PR](https://github.com/free5gc/amf/pull/68).
Please check it.

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

Thanks for the PR.
