### ISSUE TITLE
Unable to build the library

### ISSUE THREAD

**Issue by niranjankhare** [free5gc/amf#82]
Hello,
I'm trying to build the library locally, but the build fails with compile errors, from a dependancy:
 
`# git.cs.nctu.edu.tw/calee/sctp
/Users/niru/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:446:15: assignment mismatch: 4 variables but c.SCTPRead returns 3 values
/Users/niru/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:723:18: assignment mismatch: 4 variables but c.conn.SCTPRead returns 3 values
/Users/niru/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:788:28: too many arguments in call to listenSCTPExtConfig
        have (string, *SCTPAddr, InitMsg, *RtoInfo, *AssocInfo, func(string, string, syscall.RawConn) error)
        want (string, *SCTPAddr, InitMsg, func(string, string, syscall.RawConn) error)
/Users/niru/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:792:26: too many arguments in call to dialSCTPExtConfig
        have (string, *SCTPAddr, *SCTPAddr, InitMsg, *RtoInfo, *AssocInfo, func(string, string, syscall.RawConn) error)
        want (string, *SCTPAddr, *SCTPAddr, InitMsg, func(string, string, syscall.RawConn) error)
`

I'm compiling with go 1.14:

`go version
go version go1.14.15 darwin/amd64
`
Does the sctp library dependency need fixes, or amf needs to update the dependency to one that works?

Thanks in advance!

**Comment by andy89923** [comment]
Hello, sorry for the late reply. Please follow the instructions [here](https://free5gc.org/guide/3-install-free5gc/). 
If you encounter any more problems, open an issue at the free5GC repo. https://github.com/free5gc/free5gc
